version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: energy-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: energy_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: energy
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
